select * from colaboradores;
select * from colaborador_participa_projeto;
select * from contatos;
select * from emails;
select * from links_colaboradores;
select * from mensagens;
select * from parceiros;
select * from projetos;
select * from telefones;